name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.25
  - pandas=2.0.0
  - jupyterlab=4.0.5
  - pip
  - pip:
      - streamlit==1.26.0
      - streamlit-extras==0.3.0
      - streamlit-autorefresh==1.0.1

