name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - matplotlib
  - jupyterlab
  - pip
  - pip:
      - streamlit==1.26.0
      - streamlit-extras==0.3.0
      - streamlit-autorefresh==1.0.1

